# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bd < Formula
  desc "AI-supervised issue tracker for coding workflows"
  homepage "https://github.com/steveyegge/beads"
  version "0.63.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveyegge/beads/releases/download/v0.63.3/beads_0.63.3_darwin_amd64.tar.gz"
      sha256 "de5d72b22e08c9b8c5c8438dc2d83158993c649e3f880dfb227888a25f399b9c"

      define_method(:install) do
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveyegge/beads/releases/download/v0.63.3/beads_0.63.3_darwin_arm64.tar.gz"
      sha256 "2b3ab41dd74a3c2a79bc47dd0b36c0a63a2c5d76f1e3081db5288d294124f245"

      define_method(:install) do
        bin.install "bd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.63.3/beads_0.63.3_linux_amd64.tar.gz"
      sha256 "5f4efd2e010209b3f381dbcd783b2a3a652f50ea72f40ef04c8ba434d408bf9e"
      define_method(:install) do
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.63.3/beads_0.63.3_linux_arm64.tar.gz"
      sha256 "23d41884130aa524da00861949358db04bb91d6339afd35122ca06b207e7df94"
      define_method(:install) do
        bin.install "bd"
      end
    end
  end
end
