# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bd < Formula
  desc "AI-supervised issue tracker for coding workflows"
  homepage "https://github.com/steveyegge/beads"
  version "0.57.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveyegge/beads/releases/download/v0.57.0/beads_0.57.0_darwin_amd64.tar.gz"
      sha256 "289aa32d79eaa298f2ec252654aa6ebe5dd6b2a3becfd4928f1959b03df5e274"

      define_method(:install) do
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveyegge/beads/releases/download/v0.57.0/beads_0.57.0_darwin_arm64.tar.gz"
      sha256 "fbbcbdff64da29f72fbe939d4cc285305d73e830889919d182c4c6826a338ced"

      define_method(:install) do
        bin.install "bd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.57.0/beads_0.57.0_linux_amd64.tar.gz"
      sha256 "f8629d5627bed7d25f06f92334addc171d679f9aed9d08c5d42a9684205dc04b"
      define_method(:install) do
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.57.0/beads_0.57.0_linux_arm64.tar.gz"
      sha256 "84cc6b5b69dbf3900a0e0787e2f740846df4398129fc215250c83d6467b1afa8"
      define_method(:install) do
        bin.install "bd"
      end
    end
  end
end
